export const GET_LINKS_LIST = "GET_LINKS_LIST"
export const GET_LINK = "GET_LINK"
export const CREATE_LINK = "CREATE_LINK"
export const UPDATE_LINK = "UPDATE_LINK"
export const LINK_LOADING = "LINK_LOADING"
export const RESET_LINKS = "RESET_LINKS"